# Generated by Django 3.1.5 on 2021-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('h', 'High Priority'), ('m', 'Medium Priority'), ('l', 'Low Priority')], default='l', help_text='Priority', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('r', 'Review'), ('s', 'Started'), ('f', 'Finished')], default='p', help_text='Status', max_length=1),
        ),
    ]
